name: inner-text-searcher-go

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
       go-version: '1.17.6'
    - name: Install Python Dependencies
      run:
        sudo apt-get -y install python3-pip &&
        python -m pip install --upgrade pip &&
        pip3 install omni-coveragereporter &&
        pip3 install GitPython &&
        pip3 install requests

    - name: Install Go Packages
      run: cd string-distance &&
           source setup.sh && go get -t -v github.com/stretchr/testify/assert &&
           source setup.sh && go get -t -v github.com/jesperancinha/string.distance/algorithms

    - name: Run Go Tests
      run: cd string-distance && source setup.sh && go test -coverprofile=../coverage.out

    - name: Send reports
      run: omni_coveragereporter_python.py
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
